# Setup
title:               Yeray Santana-Falcón
tagline:             'PhD in Oceanography. Dispersed-minded.'
description:         'Here you would find hints from my research and my beginnings in photo and writing.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              yerasf
  url:               https://github.com/ysantanaf
  email:             yeraysf@gmail.com

# Custom vars
version:             1.0.0
